site_name: UTA-manager
theme: cinder
pages:
  - 'Главная': 'index.md'
  - 'Скрипты': 'scripts.md'
  - 'client': 'client.md'
  - 'bundle':
    - 'bundle': 'bundle/index.md'
    - 'Call Tracking': 'bundle/call-tracking.md'
    - 'Формы':
      - 'С интерфейсом ("закрытые")': 'bundle/forms/ui.md'
      - 'Встраиваемые ("открытые"")': 'bundle/forms/attach.md'
    - 'Обратный звонок': 'bundle/callback.md'
    - 'Виджет': 'bundle/widget.md'
markdown_extensions:
  - markdown_include.include
